// Default/seed data for the website
export const defaultServices = [
  {
    title: "AI Solutions & Integration",
    description: "Custom AI systems, intelligent automation, and seamless AI integrations tailored to your business needs.",
    icon: "Brain",
    category: "AI",
    features: ["AI Application Development", "LLM Integration", "RAG Systems", "AI Agents", "Prompt Engineering"],
    is_visible: true,
    order_index: 0,
  },
  {
    title: "Machine Learning Systems",
    description: "End-to-end ML pipelines, model development, training, optimization and deployment at scale.",
    icon: "Cpu",
    category: "AI",
    features: ["Model Development", "Model Training & Optimization", "Generative AI", "Data Pipelines", "ML Ops"],
    is_visible: true,
    order_index: 1,
  },
  {
    title: "Web Application Development",
    description: "High-performance, scalable web applications built with modern frameworks and best practices.",
    icon: "Globe",
    category: "Software",
    features: ["Frontend Development", "Backend Development", "Full Stack", "API Development", "SaaS Platforms"],
    is_visible: true,
    order_index: 2,
  },
  {
    title: "Mobile Application Development",
    description: "Native and cross-platform mobile apps delivering exceptional user experiences on iOS and Android.",
    icon: "Smartphone",
    category: "Software",
    features: ["iOS Development", "Android Development", "Cross-Platform", "UI/UX Design", "App Store Deployment"],
    is_visible: true,
    order_index: 3,
  },
  {
    title: "Intelligent Automation",
    description: "Workflow automation, process optimization, and autonomous systems to supercharge your operations.",
    icon: "Zap",
    category: "Automation",
    features: ["Workflow Automation", "Process Optimization", "RPA Solutions", "AI Agents", "System Integration"],
    is_visible: true,
    order_index: 4,
  },
]

export const defaultTeam = [
  {
    name: "Sabari",
    role: "Lead",
    designation: "Business Development Lead & Operations Head",
    department: "Commercial Division",
    bio: "Drives client acquisition, strategic partnerships, and business operations.",
    is_visible: true,
    order_index: 0,
  },
  {
    name: "Jagan",
    role: "Lead",
    designation: "Marketing Lead & BD Co-Lead",
    department: "Commercial Division",
    bio: "Leads brand strategy, marketing campaigns, and business development.",
    is_visible: true,
    order_index: 1,
  },
  {
    name: "Mohith",
    role: "Lead",
    designation: "Intelligent Systems Lead",
    department: "Technology Division",
    bio: "Heads AI, machine learning, and intelligent automation development.",
    is_visible: true,
    order_index: 2,
  },
  {
    name: "Vetri",
    role: "Lead",
    designation: "Technology Systems Lead",
    department: "Technology Division",
    bio: "Leads software engineering, full stack development, and system architecture.",
    is_visible: true,
    order_index: 3,
  },
  {
    name: "Muppidathi",
    role: "Lead",
    designation: "Product Strategy & Innovation Lead",
    department: "Technology Division",
    bio: "Drives product vision, roadmaps, UX design, and market research.",
    is_visible: true,
    order_index: 4,
  },
  {
    name: "Naveen Kumar",
    role: "Lead",
    designation: "Infrastructure & Quality Lead",
    department: "Technology Division",
    bio: "Oversees cloud infrastructure, DevOps, security, and quality assurance.",
    is_visible: true,
    order_index: 5,
  },
  {
    name: "Saran",
    role: "Pro",
    designation: "Full Stack Developer & AI Engineer",
    department: "Technology Division",
    bio: "Expert in full stack development and AI systems integration.",
    is_visible: true,
    order_index: 6,
  },
  {
    name: "Komal",
    role: "Pro",
    designation: "AI Developer & Frontend Engineer",
    department: "Technology Division",
    bio: "Specializes in AI applications and crafting exceptional user interfaces.",
    is_visible: true,
    order_index: 7,
  },
  {
    name: "Naveen",
    role: "Pro",
    designation: "Finance & Operations Specialist",
    department: "Commercial Division",
    bio: "Manages financial planning, reporting, and operational efficiency.",
    is_visible: true,
    order_index: 8,
  },
  {
    name: "Barath",
    role: "Pro",
    designation: "Brand & Marketing Specialist",
    department: "Commercial Division",
    bio: "Creates compelling brand identities and executes marketing campaigns.",
    is_visible: true,
    order_index: 9,
  },
  {
    name: "Girivasan",
    role: "Pro",
    designation: "Creative Media Designer",
    department: "Commercial Division",
    bio: "Crafts stunning visuals, motion graphics, and creative media content.",
    is_visible: true,
    order_index: 10,
  },
  {
    name: "Saranraj",
    role: "Pro",
    designation: "Content Strategist & SEO Specialist",
    department: "Commercial Division",
    bio: "Develops content strategy and drives organic growth through SEO.",
    is_visible: true,
    order_index: 11,
  },
  {
    name: "Sabarivasan",
    role: "Pro",
    designation: "Social Media & Community Manager",
    department: "Commercial Division",
    bio: "Manages social presence, community engagement, and brand voice.",
    is_visible: true,
    order_index: 12,
  },
]

export const defaultWorks = [
  {
    title: "AI Customer Support System",
    description: "Built an intelligent customer support automation system using RAG and LLMs, reducing response time by 70%.",
    category: "AI",
    tags: ["AI", "RAG", "LLM", "Automation"],
    is_featured: true,
    is_visible: true,
    order_index: 0,
  },
  {
    title: "E-Commerce SaaS Platform",
    description: "Full-stack multi-tenant e-commerce platform with AI-powered product recommendations and analytics.",
    category: "Software",
    tags: ["Next.js", "Node.js", "PostgreSQL", "AI"],
    is_featured: true,
    is_visible: true,
    order_index: 1,
  },
  {
    title: "Workflow Automation Suite",
    description: "End-to-end business process automation connecting 15+ tools, saving 40+ hours per week for the client.",
    category: "Automation",
    tags: ["Automation", "Integration", "AI Agents"],
    is_featured: true,
    is_visible: true,
    order_index: 2,
  },
  {
    title: "Real Estate Mobile App",
    description: "Cross-platform mobile application with AI property matching, virtual tours, and smart notifications.",
    category: "Mobile",
    tags: ["React Native", "AI", "Mobile", "UX"],
    is_featured: false,
    is_visible: true,
    order_index: 3,
  },
]

export const defaultSettings = {
  company_name: "Precision Pro's",
  tagline: "Building Tomorrow's Intelligence, Today",
  phone: "+91 98765 43210",
  whatsapp: "+91 98765 43210",
  email: "hello@precisionpros.in",
  instagram: "https://instagram.com/precisionpros",
  linkedin: "https://linkedin.com/company/precisionpros",
  youtube: "https://youtube.com/@precisionpros",
  show_works: "true",
  show_team: "true",
  show_services: "true",
  show_contact: "true",
  total_projects: "20",
  happy_clients: "15",
  team_size: "13",
}
